@extends('layouts.public')

@section('title', 'Mela AI Privacy Policy | Armely')
@section('meta_description', 'Learn how Armely collects, uses, protects, retains, and shares information when organizations use Mela Meeting Assistant.')
@section('canonical_url', route('mela.privacy'))

@push('head')
<meta name="robots" content="index,follow">
<meta property="og:title" content="Mela AI Privacy Policy | Armely">
<meta property="og:description" content="Privacy information for Mela Meeting Assistant and its Microsoft 365 integrations.">
<meta property="og:url" content="{{ route('mela.privacy') }}">
@endpush

@push('styles')
@include('legal.partials.mela-policy-styles')
@endpush

@section('content')
<main class="mela-legal">
  <header class="mela-legal-hero"><div class="mela-legal-container">
    <span class="mela-legal-badge">Mela AI</span>
    <h1>Privacy Policy</h1>
    <p>This Policy explains how Armely handles information when organizations deploy and use Mela Meeting Assistant with Microsoft Teams, Planner, Outlook, and Microsoft 365.</p>
    <div class="mela-legal-meta"><span>Effective: August 5, 2026</span><span>Last updated: August 5, 2026</span></div>
    <div class="mela-legal-links"><a href="{{ route('mela-meeting-assistant') }}">Mela Meeting Assistant</a><a href="{{ route('mela.terms') }}">Mela Terms of Use</a></div>
  </div></header>
  <div class="mela-legal-body"><div class="mela-legal-container mela-legal-layout">
    <aside class="mela-legal-toc"><strong>On this page</strong><div>
      <a href="#scope">1. Scope</a><a href="#roles">2. Privacy Roles</a><a href="#information">3. Information We Process</a><a href="#sources">4. Sources</a><a href="#uses">5. How We Use Information</a><a href="#ai-processing">6. AI Processing</a><a href="#sharing">7. Sharing</a><a href="#microsoft">8. Microsoft 365</a><a href="#retention">9. Retention</a><a href="#security">10. Security</a><a href="#transfers">11. Transfers</a><a href="#choices">12. Rights and Choices</a><a href="#children">13. Children</a><a href="#changes">14. Changes</a><a href="#contact">15. Contact</a>
    </div></aside>
    <article class="mela-legal-document">
      <section id="scope"><h2>1. Scope</h2><p>This Mela AI Privacy Policy ("Policy") applies to Mela Meeting Assistant and related Mela administration, support, pilot, and product experiences provided by Armely, LLC ("Armely," "we," "us"). It supplements Armely's general website privacy policy.</p><p>This Policy does not govern Microsoft products, Customer-controlled Microsoft 365 environments, or third-party services, which are subject to their own terms and privacy notices.</p></section>
      <section id="roles"><h2>2. Our Privacy Roles</h2><p>For meeting content and other information submitted through a Customer's Microsoft 365 tenant, the Customer generally determines why and how information is processed. In that context, Customer acts as the data controller or business, and Armely acts as a processor or service provider on Customer's instructions.</p><p>Armely acts as an independent controller for account administration, billing, security monitoring, support communications, product analytics, and legal compliance. A data processing agreement may provide additional terms.</p></section>
      <section id="information"><h2>3. Information We Process</h2><h3>Customer and user information</h3><ul><li>names, business email addresses, organization, job title, user and tenant identifiers;</li><li>subscription, pilot, licensing, support, and administrative contact information;</li><li>authentication events, permissions, configuration, and role information.</li></ul><h3>Meeting and workflow information</h3><ul><li>meeting identifiers, title, date, time, organizer, attendees, and participation metadata;</li><li>meeting chat, transcript, notes, or other content made available to Mela by authorized users and tenant configuration;</li><li>generated summaries, decisions, action items, task assignments, due dates, and follow-up content;</li><li>Planner plan and task identifiers, Outlook delivery information, and status of requested workflow actions.</li></ul><h3>Technical information</h3><ul><li>IP address, device and browser information, timestamps, diagnostics, error logs, performance events, and security telemetry;</li><li>support requests and communications with Armely.</li></ul><div class="mela-legal-callout"><p>The specific information Mela can access depends on the permissions approved by the Customer's Microsoft 365 administrator and on how authorized users invoke the Service.</p></div></section>
      <section id="sources"><h2>4. Sources of Information</h2><p>We receive information directly from Customers and users, from Customer-authorized Microsoft 365 APIs and services, from administrators configuring Mela, and automatically from use of the Service. We may also receive business contact information from implementation partners or a Customer's authorized representatives.</p></section>
      <section id="uses"><h2>5. How We Use Information</h2><p>We process information to:</p><ul><li>authenticate users and connect Mela to authorized Microsoft 365 services;</li><li>capture authorized meeting context and generate summaries, action items, tasks, and follow-ups;</li><li>create or update Planner tasks and deliver Outlook communications as requested;</li><li>configure tenants, administer subscriptions, provide support, and respond to requests;</li><li>maintain reliability, diagnose errors, prevent abuse, and protect accounts and systems;</li><li>measure feature performance and improve the Service using aggregated, de-identified, or Customer-authorized data;</li><li>comply with law, enforce agreements, and establish or defend legal claims.</li></ul><p>Where required, our legal bases may include performance of a contract, legitimate interests, consent, and compliance with legal obligations.</p></section>
      <section id="ai-processing"><h2>6. AI Processing and Model Use</h2><p>Mela uses automated and AI-enabled processing to identify discussion topics, decisions, action items, assignees, deadlines, and draft summaries. AI-generated output may be inaccurate and should be reviewed by authorized users.</p><p>Armely does not use Customer meeting content to train a general-purpose model for unrelated customers unless Customer has expressly agreed in writing. We may use de-identified and aggregated operational information to improve security, reliability, and product performance.</p></section>
      <section id="sharing"><h2>7. How We Share Information</h2><p>We may disclose information:</p><ul><li>to the Customer and its authorized administrators and users;</li><li>to infrastructure, hosting, communications, security, analytics, and support providers that process information under contract;</li><li>to Microsoft services when necessary to perform Customer-requested integrations;</li><li>to professional advisers, auditors, insurers, and transaction counterparties subject to appropriate confidentiality obligations;</li><li>when required by law or reasonably necessary to protect rights, safety, systems, users, or the public;</li><li>in connection with a merger, financing, acquisition, reorganization, or sale of assets.</li></ul><p>Armely does not sell Customer meeting content or use it for cross-context behavioral advertising.</p></section>
      <section id="microsoft"><h2>8. Microsoft 365 Integration</h2><p>Mela accesses Microsoft 365 only through permissions approved by Customer administrators or authorized users. Depending on configuration, data may be read from or written to Teams, Microsoft Graph, Planner, Outlook, Entra ID, SharePoint, or related services.</p><p>Customer controls Microsoft identities, licenses, retention policies, access permissions, and tenant security. Data stored by Microsoft remains subject to Customer's Microsoft agreements and configuration. Revoking permissions or disabling Mela may stop future access but may not delete information already retained under an applicable agreement or legal obligation.</p></section>
      <section id="retention"><h2>9. Data Retention and Deletion</h2><p>We retain information only as long as reasonably necessary to provide the Service, satisfy Customer instructions and contractual commitments, maintain security and audit records, resolve disputes, and comply with law. Retention periods vary by data type, subscription, tenant configuration, and contractual requirements.</p><p>Upon termination, Customer may request return or deletion of Customer Data as provided in the applicable agreement. Some information may remain temporarily in encrypted backups or be retained where legally required. Customer administrators remain responsible for information stored in Customer's Microsoft 365 environment.</p></section>
      <section id="security"><h2>10. Security</h2><p>Armely uses reasonable administrative, technical, and organizational safeguards designed to protect information. Measures may include access controls, least-privilege permissions, encryption in transit and where appropriate at rest, logging, monitoring, vulnerability management, and personnel confidentiality obligations.</p><p>No system is completely secure. Customers should configure appropriate Microsoft 365 controls, conditional access, retention, user training, endpoint protection, and incident procedures. Suspected security issues should be reported promptly to <a href="mailto:ask.me@armely.com">ask.me@armely.com</a>.</p></section>
      <section id="transfers"><h2>11. International Data Transfers</h2><p>Armely and its providers may process information in the United States and other countries where they operate. Where required, we use recognized transfer safeguards, contractual protections, and supplementary measures. Customer-selected Microsoft data residency and tenant settings may also affect processing locations.</p></section>
      <section id="choices"><h2>12. Privacy Rights and Choices</h2><p>Users should first direct requests concerning meeting content or Customer-controlled data to their organization's Microsoft 365 administrator or privacy contact. Where Armely acts as a processor, we assist the Customer as required by contract and law.</p><p>Depending on location and applicable law, individuals may have rights to access, correct, delete, restrict, object to, or obtain a copy of personal information, and to withdraw consent. Requests may be sent to <a href="mailto:ask.me@armely.com">ask.me@armely.com</a>. We may verify identity and authority before responding. Authorized agents may submit requests where permitted by law.</p><p>Users may stop future Mela access by asking their administrator to disable the app or revoke permissions. Email recipients may use an available unsubscribe link for optional event or marketing communications; service and security messages may still be sent.</p></section>
      <section id="children"><h2>13. Children's Privacy</h2><p>Mela is designed for organizational and workplace use and is not directed to children under 13. Customers must not knowingly use Mela to process children's personal information unless authorized by Armely in writing and configured with all legally required consents and safeguards.</p></section>
      <section id="changes"><h2>14. Changes to This Policy</h2><p>We may update this Policy to reflect changes to Mela, our practices, or legal requirements. We will post the revised Policy with a new "Last updated" date and provide additional notice where required. Material changes apply prospectively unless law permits otherwise.</p></section>
      <section id="contact"><h2>15. Contact Armely</h2><p>For privacy questions, rights requests, or concerns about Mela, contact:</p><p><strong>Armely, LLC</strong><br>Attn: Mela Privacy<br>17400 Dallas Pkwy, Suite 111<br>Dallas, TX 75287<br>United States<br><a href="mailto:ask.me@armely.com">ask.me@armely.com</a><br><a href="tel:+19724600643">+1 972 460 0643</a></p></section>
    </article>
  </div></div>
</main>
@endsection
