@extends('layouts.public')

@section('title', 'Mela Meeting Assistant Terms of Use | Armely')
@section('meta_description', 'Terms governing access to and use of Mela Meeting Assistant by organizations, administrators, and authorized users.')
@section('canonical_url', route('mela.terms'))

@push('head')
<meta name="robots" content="index,follow">
<meta property="og:title" content="Mela Meeting Assistant Terms of Use | Armely">
<meta property="og:description" content="Terms governing access to and use of Mela Meeting Assistant.">
<meta property="og:url" content="{{ route('mela.terms') }}">
@endpush

@push('styles')
@include('legal.partials.mela-policy-styles')
@endpush

@section('content')
<main class="mela-legal">
  <header class="mela-legal-hero"><div class="mela-legal-container">
    <span class="mela-legal-badge">Mela Meeting Assistant</span>
    <h1>Terms of Use</h1>
    <p>These Terms govern access to and use of Mela Meeting Assistant, including its Microsoft Teams, Planner, Outlook, and related Microsoft 365 integrations.</p>
    <div class="mela-legal-meta"><span>Effective: August 5, 2026</span><span>Last updated: August 5, 2026</span></div>
    <div class="mela-legal-links"><a href="{{ route('mela-meeting-assistant') }}">Mela Meeting Assistant</a><a href="{{ route('mela.privacy') }}">Mela Privacy Policy</a></div>
  </div></header>
  <div class="mela-legal-body"><div class="mela-legal-container mela-legal-layout">
    <aside class="mela-legal-toc"><strong>On this page</strong><div>
      <a href="#agreement">1. Agreement</a><a href="#service">2. The Service</a><a href="#accounts">3. Accounts and Authority</a><a href="#acceptable-use">4. Acceptable Use</a><a href="#meetings">5. Meeting Responsibilities</a><a href="#data">6. Customer Data</a><a href="#ai">7. AI-Generated Output</a><a href="#microsoft">8. Microsoft Services</a><a href="#fees">9. Fees and Pilots</a><a href="#ip">10. Intellectual Property</a><a href="#confidentiality">11. Confidentiality</a><a href="#availability">12. Availability</a><a href="#disclaimers">13. Disclaimers</a><a href="#liability">14. Liability</a><a href="#termination">15. Termination</a><a href="#general">16. General Terms</a><a href="#contact">17. Contact</a>
    </div></aside>
    <article class="mela-legal-document">
      <section id="agreement"><h2>1. Agreement to These Terms</h2><p>These Terms of Use ("Terms") are a legal agreement between Armely, LLC ("Armely," "we," "us") and the organization or person accessing Mela Meeting Assistant ("Customer," "you"). By installing, enabling, administering, or using Mela, you agree to these Terms.</p><p>If you use Mela for an organization, you represent that you have authority to bind that organization. If a separate order form, subscription agreement, statement of work, or data processing agreement applies, that agreement controls to the extent of a conflict.</p></section>
      <section id="service"><h2>2. The Service</h2><p>Mela Meeting Assistant is an enterprise productivity service that can process authorized Microsoft Teams meeting content and create summaries, action items, Microsoft Planner tasks, Outlook follow-ups, and related workflow outputs. Features may depend on the Customer's subscription, tenant configuration, permissions, and Microsoft service availability.</p><p>Armely may improve or modify features while preserving the material functionality of paid subscriptions. Preview, beta, trial, and pilot features may change or be discontinued.</p></section>
      <section id="accounts"><h2>3. Accounts, Tenant Administration, and Authority</h2><ul><li>Customer administrators are responsible for approving Mela, granting appropriate Microsoft Entra ID permissions, configuring meeting policies, and managing authorized users.</li><li>You must protect credentials, tokens, tenant identifiers, and administrative access and promptly report suspected unauthorized use.</li><li>You may permit only authorized workforce members and contractors to use Mela for Customer's legitimate business purposes.</li><li>You are responsible for user activity and for ensuring that tenant configuration complies with your policies and applicable law.</li></ul></section>
      <section id="acceptable-use"><h2>4. Acceptable Use</h2><p>You may not use Mela to:</p><ul><li>violate law, privacy rights, confidentiality duties, employment obligations, or contractual restrictions;</li><li>capture or process a meeting without required notice, consent, or authorization;</li><li>upload malicious code, interfere with the Service, bypass security, or test vulnerabilities without written permission;</li><li>reverse engineer, copy, resell, sublicense, or use the Service to build a competing product except where law prohibits such restrictions;</li><li>generate unlawful, deceptive, discriminatory, harassing, or harmful content;</li><li>process highly sensitive information unless expressly authorized by Armely in writing and supported by the applicable agreement and configuration.</li></ul></section>
      <section id="meetings"><h2>5. Meeting Notice, Consent, and Workplace Responsibilities</h2><div class="mela-legal-callout"><p><strong>Customer controls when Mela is invited and used.</strong> Customer is responsible for providing legally required notices and obtaining consents from participants.</p></div><p>Laws and organizational policies governing transcription, monitoring, recording, workplace privacy, biometric information, and communications vary. Mela's technical behavior does not replace Customer's legal obligations. Customer must establish appropriate policies, user training, retention rules, and access controls.</p></section>
      <section id="data"><h2>6. Customer Data</h2><p>As between the parties, Customer retains its rights in meeting content, prompts, files, participant information, configurations, and other data submitted to the Service ("Customer Data"). Customer grants Armely a limited right to host, process, transmit, and display Customer Data only as needed to provide, secure, support, and improve the Service in accordance with the applicable agreement and the <a href="{{ route('mela.privacy') }}">Mela AI Privacy Policy</a>.</p><p>Customer represents that it has all rights and permissions necessary for Armely to process Customer Data as instructed. Armely does not acquire ownership of Customer Data.</p></section>
      <section id="ai"><h2>7. AI-Generated Output</h2><p>Mela uses automated systems to generate summaries, decisions, tasks, due dates, and other outputs. These outputs may be incomplete, inaccurate, or contextually incorrect. Users must review outputs before relying on them, distributing them, or posting tasks to Planner.</p><p>Mela is not a substitute for legal, medical, financial, safety, human-resources, or other professional judgment. Customer remains responsible for decisions and actions based on output.</p></section>
      <section id="microsoft"><h2>8. Microsoft and Third-Party Services</h2><p>Mela interoperates with Microsoft 365 services that are governed by Customer's agreements with Microsoft. Armely does not control Microsoft service availability, licensing, APIs, security policies, or product changes. Customer is responsible for maintaining required Microsoft licenses and configurations.</p><p>Microsoft names and marks belong to Microsoft. Armely is not responsible for third-party services outside its reasonable control.</p></section>
      <section id="fees"><h2>9. Fees, Subscriptions, Trials, and Taxes</h2><p>Paid use is subject to the pricing, usage limits, subscription term, and payment terms in the applicable order. Unless stated otherwise, fees are non-refundable and exclude taxes. Customer is responsible for applicable taxes other than taxes on Armely's net income.</p><p>Trials and pilots are provided for evaluation during the stated period and may have limited functionality, support, or capacity. Armely may end a trial or pilot at any time unless an applicable signed agreement states otherwise.</p></section>
      <section id="ip"><h2>10. Intellectual Property and Feedback</h2><p>Armely and its licensors retain all rights in Mela, its software, models, workflows, documentation, interfaces, branding, and improvements. Except for the limited right to use the Service during an active subscription, no rights are transferred.</p><p>If you provide feedback, you grant Armely a perpetual, worldwide, royalty-free right to use it without identifying you or disclosing Customer Confidential Information.</p></section>
      <section id="confidentiality"><h2>11. Confidentiality and Security</h2><p>Each party will protect the other's non-public confidential information using reasonable care and use it only to perform the applicable agreement. Confidentiality obligations do not apply to information lawfully known without restriction, independently developed, publicly available through no breach, or rightfully received from another source.</p><p>Armely maintains reasonable administrative, technical, and organizational safeguards. No system is completely secure, and Customer must use appropriate tenant controls, permissions, and endpoint security.</p></section>
      <section id="availability"><h2>12. Availability, Support, and Changes</h2><p>Armely will use commercially reasonable efforts to provide the Service. Scheduled maintenance, emergency maintenance, Microsoft outages, internet failures, security events, and force majeure may affect availability. Any service levels or support commitments apply only if included in a signed agreement.</p></section>
      <section id="disclaimers"><h2>13. Disclaimers</h2><p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SERVICE, TRIALS, AND AI-GENERATED OUTPUTS ARE PROVIDED "AS IS" AND "AS AVAILABLE." ARMELY DISCLAIMS IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, AND ANY WARRANTY THAT OUTPUT WILL BE ERROR-FREE OR MEET CUSTOMER'S REQUIREMENTS.</p></section>
      <section id="liability"><h2>14. Limitation of Liability</h2><p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, NEITHER PARTY WILL BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR FOR LOST PROFITS, REVENUE, GOODWILL, OR DATA. ARMELY'S AGGREGATE LIABILITY ARISING FROM THE SERVICE WILL NOT EXCEED THE FEES PAID OR PAYABLE FOR MELA DURING THE 12 MONTHS BEFORE THE EVENT GIVING RISE TO LIABILITY. THESE LIMITS DO NOT APPLY WHERE THEY ARE PROHIBITED BY LAW OR TO LIABILITY THAT CANNOT LEGALLY BE LIMITED.</p></section>
      <section id="termination"><h2>15. Suspension and Termination</h2><p>Armely may suspend access when reasonably necessary to address a security risk, unlawful use, material breach, non-payment, or harm to the Service or others. Either party may terminate as provided in the applicable order or agreement. On termination, Customer must stop using Mela. Data return and deletion will follow the applicable agreement and Privacy Policy.</p></section>
      <section id="general"><h2>16. General Terms</h2><p>These Terms and incorporated agreements are the complete agreement regarding Mela. You may not assign them without Armely's written consent, except in connection with a merger or sale of substantially all assets. If a provision is unenforceable, the remaining provisions remain effective. Failure to enforce a provision is not a waiver.</p><p>These Terms are governed by the laws of the State of Texas, without regard to conflict-of-laws principles. State and federal courts located in Dallas County, Texas will have exclusive jurisdiction, unless an applicable signed agreement provides otherwise.</p><p>Armely may update these Terms. Material changes will be posted with a revised effective date and, where required, additional notice.</p></section>
      <section id="contact"><h2>17. Contact</h2><p>Questions about these Terms may be sent to <a href="mailto:ask.me@armely.com">ask.me@armely.com</a> or:</p><p><strong>Armely, LLC</strong><br>17400 Dallas Pkwy, Suite 111<br>Dallas, TX 75287<br>United States<br><a href="tel:+19724600643">+1 972 460 0643</a></p></section>
    </article>
  </div></div>
</main>
@endsection
