@php
    $emailTitle = $emailTitle ?? 'Armely Notification';
    $emailBadge = $emailBadge ?? 'Armely';
    $emailAccent = $emailAccent ?? '#2F5597';
    $logoUrl = 'https://armely.com/store/images/logo/armely-store-logo.png';
@endphp
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="x-apple-disable-message-reformatting"><title>{{ $emailTitle }}</title>
<style>@media only screen and (max-width:620px){.mail-shell{padding:6px 3px 14px!important}.mail-header,.mail-body,.mail-footer{padding:13px 10px!important}.mail-logo-cell{width:56px!important;padding-right:9px!important}.mail-logo-box{width:48px!important;height:40px!important;padding:3px!important}.mail-logo{width:48px!important;max-height:40px!important}.mail-title{font-size:19px!important}.mail-detail-label,.mail-detail-value{display:block!important;width:100%!important;text-align:left!important;box-sizing:border-box!important}.mail-detail-label{padding-bottom:2px!important}.mail-detail-value{padding-top:2px!important}.mail-button{display:block!important;text-align:center!important}}</style></head>
<body style="margin:0;padding:0;background:#eef3fa;font-family:'Segoe UI',Arial,sans-serif;color:#1f2937;"><div class="mail-shell" style="max-width:760px;margin:0 auto;padding:20px 10px 30px;"><div style="background:#fff;border:1px solid #dbe7f7;border-radius:16px;overflow:hidden;box-shadow:0 10px 28px rgba(15,47,99,.10);">
<div class="mail-header" style="background:#0f2f63;padding:20px 24px;"><table role="presentation" cellpadding="0" cellspacing="0" width="100%"><tr><td class="mail-logo-cell" width="92" style="width:92px;padding-right:18px;vertical-align:middle"><div class="mail-logo-box" style="width:78px;height:64px;padding:5px;background:#fff;border-radius:10px"><img class="mail-logo" src="{{ $logoUrl }}" width="78" alt="Armely" style="display:block;width:78px;max-height:64px;height:auto"></div></td><td style="vertical-align:middle"><span style="display:inline-block;margin-bottom:6px;padding:4px 11px;border-radius:20px;background:{{ $emailAccent }};color:#fff;font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.06em">{{ $emailBadge }}</span><p style="margin:0 0 4px;color:#dbe7ff;font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.08em">Armely AI Solutions</p><h1 class="mail-title" style="margin:0;color:#fff!important;font-size:24px;line-height:1.2">{{ $emailTitle }}</h1></td></tr></table></div>
<div class="mail-body" style="padding:24px 28px;font-size:14px;line-height:1.65">@yield('content')</div>
<div class="mail-footer" style="padding:15px 28px 18px;background:#f8fbff;border-top:1px solid #e3ebf8;color:#7b8fad;font-size:11px">@yield('footer', 'This is an automated message from Armely AI Solutions.')</div>
</div></div></body></html>
